online_store/cart/urls.py
from django.urls import path

from .views import *


app_name = 'cart'

urlpatterns = [
    path('', cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', cart_add, name='cart_add'),
    path('remove/<int:product_id>/', cart_remove, name='cart_remove'),
]

online_store/coupons/urls.py
from django.urls import path

from .views import *


app_name = 'coupons'

urlpatterns = [
    path('apply/', coupon_apply, name='apply'),
]

online_store/online_store/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('cart/', include('cart.urls', namespace='cart')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('payment/', include('payment.urls', namespace='payment')),
    path('coupons/', include('coupons.urls', namespace='coupons')),
    path('', include('store.urls', namespace='store')),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)
    

online_store/orders/urls.py
from django.urls import path

from .views import *


app_name = 'orders'


urlpatterns = [
    path('create/', order_create, name='order_create'),
    path('admin/order/<int:order_id>/', admin_order_detail, name='admin_order_detail'),
    path('admin/order/<int:order_id>/pdf/', admin_order_pdf, name='admin_order_pdf'),
]

online_store/store/urls.py
from django.urls import path

from .views import *


app_name = 'store'

urlpatterns = [
    path('', ProductListView.as_view(), name='product_list'),
    path('<slug:category_slug>/', ProductListView.as_view(), name='product_list_by_category'),
    path('<int:id>/<slug:slug>/', product_detail, name='product_detail'),
]

online_store/cart/forms.py
from django import forms


PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 21)]


class CartAddProductForm(forms.Form):
    quantity = forms.TypedChoiceField(choices=PRODUCT_QUANTITY_CHOICES,
                                      coerce=int,
                                      label='Кол-во')
    override = forms.BooleanField(required=False,
                                  initial=False,
                                  widget=forms.HiddenInput)

online_store/cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST

from store.models import Product
from .cart import Cart
from .forms import CartAddProductForm
from coupons.forms import CouponApplyForm


@require_POST
def cart_add(request, product_id):
    """ Добавляет товар в корзину """
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    form = CartAddProductForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(product=product,
                 quantity=cd['quantity'],
                 override_quantity=cd['override'])
    return redirect('cart:cart_detail')


@require_POST
def cart_remove(request, product_id):
    """ Удаляет товар из корзины """
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    cart.remove(product)
    return redirect('cart:cart_detail')


def cart_detail(request):
    """ Отображает содержимое корзины """
    cart = Cart(request)
    for item in cart:
        item['update_quantity_form'] = CartAddProductForm(initial={
                            'quantity': item['quantity'],
                            'override': True})

    coupon_apply_form = CouponApplyForm()
    
    return render(request=request, 
                  template_name='cart/detail.html', 
                  context={
                      'cart': cart,
                      'coupon_apply_form': coupon_apply_form,
                        })

online_store/cart/templates/cart/detail.html
{% extends "store/base.html" %}
{% load static %}

{% block title %}
Моя корзина
{% endblock %}

{% block content %}
  <h1>Моя корзина</h1>
  <table class="cart">
    <thead>
      <tr>
        <th>Фото товара</th>
        <th>Название</th>
        <th>Кол-во</th>
        <th>Удалить</th>
        <th>Цена за 1 шт.</th>
        <th>Общая цена</th>
      </tr>
    </thead>
    <tbody>
      {% for item in cart %}
        {% with product=item.product %}
          <tr>
            <td>
              <a href="{{ product.get_absolute_url }}">
                <img src="{% if product.image %}{{ product.image.url }}
                {% else %}{% static 'img/no_image.png' %}{% endif %}">
              </a>
            </td>
            <td>{{ product.name }}</td>
            <td>
              <form action="{% url 'cart:cart_add' product.id %}" method="post">
                {{ item.update_quantity_form.quantity }}
                {{ item.update_quantity_form.override }}
                <input type="submit" value="Обновить">
                {% csrf_token %}
              </form>
            </td>
            <td>
              <form action="{% url 'cart:cart_remove' product.id %}" method="post">
                <input type="submit" value="Удалить">
                {% csrf_token %}
              </form>
            </td>
            <td class="num">{{ item.price }}₽</td>
            <td class="num">{{ item.total_price }}₽</td>
          </tr>
        {% endwith %}
      {% endfor %}
      {% if cart.coupon %}
        <tr class="subtotal">
          <td>Подытог</td>
          <td colspan="4"></td>
          <td class="num">{{ cart.get_total_price|floatformat:2 }}₽</td>
        </tr>
        <tr>
          <td>
            Промокод "{{ cart.coupon.code }}"
            (скидка {{ cart.coupon.discount }}%)
          </td>
          <td colspan="4"></td>
          <td class="num neg">
            - {{ cart.get_discount|floatformat:2 }}₽
          </td>
        </tr>
      {% endif %}
      <tr class="total">
        <td>Итого</td>
        <td colspan="4"></td>
        <td class="num">{{ cart.get_total_price_after_discount|floatformat:2 }}₽</td>
      </tr>
    </tbody>
  </table>
  <p>Применить промокод:</p>
  <form action="{% url 'coupons:apply' %}" method="post">
    {{ coupon_apply_form }}
    <input type="submit" value="Применить">
    {% csrf_token %}
  </form>
  <p class="text-right">
    <a href="{% url 'store:product_list' %}" class="button light">Продолжить покупки</a>
    <a href="{% url 'orders:order_create' %}" class="button">Заказать</a>
  </p>
{% endblock %}